### ISSUE TITLE
Crash on initializing game progress

### ISSUE THREAD

**Issue by QianFuv** [elbaronjack/GreenDelights#4]
https://mclo.gs/XEMQ093

**Comment by elbaronjack** [comment]
I don't know... There is a problem between Kiwi and Green Delights?

**Comment by QianFuv** [comment]
I don't know the specific reason, I only know that I encountered this issue after updating the version

**Comment by elbaronjack** [comment]
Okey it's looking for the mod Brewin an Chewin, there is a problem in the integration

**Comment by QianFuv** [comment]
Maybe, plz check it.orz

**Comment by elbaronjack** [comment]
I can't replicate the crash :C I made a new profile only with JEI, Farmer's Delight and Green Delgihts, it works has intended... Then I installed Brewin and Chewin (it was working well) and removed it, and it still working properly... 

I suggest you to download the previous version, sry -.-

**Comment by QianFuv** [comment]
I will obtain the minimum test sample set through testing later, please look forward to my subsequent updates.

**Comment by elbaronjack** [comment]
I made an update today, check if the crash is fixed, pls

**Comment by QianFuv** [comment]
When a new version appears on CurseForge, I will test it immediately.

**Comment by QianFuv** [comment]
Alternatively, you can send me the new version here :)

**Comment by elbaronjack** [comment]
Update is online

**Comment by QianFuv** [comment]
still crash
report: https://mclo.gs/nLjV2xs
I noticed in the update log that you mentioned this bug was caused by not installing Chewin and Brewin, but in reality, I have installed Chewin and Brewin.

**Comment by elbaronjack** [comment]
Oh my...

**Comment by elbaronjack** [comment]
Try to load a game without brewin and chewin

**Comment by QianFuv** [comment]
NO any crash

**Comment by elbaronjack** [comment]
Ok... If there is no crash without BC... I think the problem is I'm using items of BC before it is loaded... I need to ensure my mod is always loading after BC at the moment I try to use it dependecies... I must work on it!

**Comment by QianFuv** [comment]
Looking forward to your update!

**Comment by elbaronjack** [comment]
I upload a new version, wait for it and try, pls

**Comment by QianFuv** [comment]
Crash also: https://mclo.gs/XLC9Au1

**Comment by QianFuv** [comment]
I regret to inform you that I am unable to continue tracking this issue.
